AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Collab drawing tool
Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 30
Resources:
  MainFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handlers.handler
      Runtime: nodejs12.x
      CodeUri: lib
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /
            Method: GET 
Outputs:
  ApiURL:
    Description: "API endpoint URL for Prod environment"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"